version: "3.8"
services:
  linuxgsm:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.cs
    container_name: counterstrike
    restart: unless-stopped
    ports:
      - "27015:27015/tcp"
      - "27015:27015/udp"
      - "27020:27020/udp"
      - "27005:27005/udp"
