version: "3.8"
services:
  # bind mount example
  linuxgsm-etl-bind:
    image: gameservermanagers/gameserver:etl
    # image: ghcr.io/gameservermanagers/gameserver:etl
    container_name: etlserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-etl-volume:
    image: gameservermanagers/gameserver:etl
    # image: ghcr.io/gameservermanagers/gameserver:etl
    container_name: etlserver
    restart: unless-stopped
    volumes:
      - linuxgsm-etl:/data
    ports:

volumes:
  linuxgsm-etl:
