version: "3.8"
services:
  # bind mount example
  linuxgsm-ricochet-bind:
    image: gameservermanagers/gameserver:ricochet
    # image: ghcr.io/gameservermanagers/gameserver:ricochet
    container_name: ricochetserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/ricochetserver:/data
    ports:

  # volume example
  linuxgsm-ricochet-volume:
    image: gameservermanagers/gameserver:ricochet
    # image: ghcr.io/gameservermanagers/gameserver:ricochet
    container_name: ricochetserver
    restart: unless-stopped
    volumes:
      - linuxgsm-ricochet:/data
    ports:

volumes:
  linuxgsm-ricochet:
