version: "3.8"
services:
  # bind mount example
  linuxgsm-zmr-bind:
    image: ghcr.io/gameservermanagers/gameserver:zmr
    container_name: zmrserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-zmr-volume:
    image: ghcr.io/gameservermanagers/gameserver:zmr
    container_name: zmrserver
    restart: unless-stopped
    volumes:
      - linuxgsm-zmr:/data
    ports:

volumes:
  linuxgsm-zmr:
