version: "3.8"
services:
  linuxgsm-ats:
    image: ghcr.io/gameservermanagers/gameserver:ats
    container_name: atsserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
