version: "3.8"
services:
  linuxgsm-vs:
    image: ghcr.io/gameservermanagers/gameserver:vs
    container_name: vsserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
