version: "3.8"
services:
  # bind mount example
  linuxgsm-hw-bind:
    image: ghcr.io/gameservermanagers/gameserver:hw
    container_name: hwserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-hw-volume:
    image: ghcr.io/gameservermanagers/gameserver:hw
    container_name: hwserver
    restart: unless-stopped
    volumes:
      - linuxgsm-hw:/data
    ports:

volumes:
  linuxgsm-hw:
