version: "3.8"
services:
  # bind mount example
  linuxgsm-tf2-bind:
    image: gameservermanagers/gameserver:tf2
    # image: ghcr.io/gameservermanagers/gameserver:tf2
    container_name: tf2server
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/tf2server:/data
    ports:

  # volume example
  linuxgsm-tf2-volume:
    image: gameservermanagers/gameserver:tf2
    # image: ghcr.io/gameservermanagers/gameserver:tf2
    container_name: tf2server
    restart: unless-stopped
    volumes:
      - linuxgsm-tf2:/data
    ports:

volumes:
  linuxgsm-tf2:
