version: "3.8"
services:
  # bind mount example
  linuxgsm-wmc-bind:
    image: gameservermanagers/gameserver:wmc
    # image: ghcr.io/gameservermanagers/gameserver:wmc
    container_name: wmcserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/wmcserver:/data
    ports:

  # volume example
  linuxgsm-wmc-volume:
    image: gameservermanagers/gameserver:wmc
    # image: ghcr.io/gameservermanagers/gameserver:wmc
    container_name: wmcserver
    restart: unless-stopped
    volumes:
      - linuxgsm-wmc:/data
    ports:

volumes:
  linuxgsm-wmc:
