version: "3.8"
services:
  # bind mount example
  linuxgsm-cscz-bind:
    image: ghcr.io/gameservermanagers/gameserver:cscz
    container_name: csczserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-cscz-volume:
    image: ghcr.io/gameservermanagers/gameserver:cscz
    container_name: csczserver
    restart: unless-stopped
    volumes:
      - linuxgsm-cscz:/data
    ports:

volumes:
  linuxgsm-cscz:
