version: "3.8"
services:
  # bind mount example
  linuxgsm-jc2-bind:
    image: ghcr.io/gameservermanagers/gameserver:jc2
    container_name: jc2server
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-jc2-volume:
    image: ghcr.io/gameservermanagers/gameserver:jc2
    container_name: jc2server
    restart: unless-stopped
    volumes:
      - linuxgsm-jc2:/data
    ports:

volumes:
  linuxgsm-jc2:
