version: "3.8"
services:
  # bind mount example
  linuxgsm-sbots-bind:
    image: gameservermanagers/gameserver:sbots
    # image: ghcr.io/gameservermanagers/gameserver:sbots
    container_name: sbotsserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-sbots-volume:
    image: gameservermanagers/gameserver:sbots
    # image: ghcr.io/gameservermanagers/gameserver:sbots
    container_name: sbotsserver
    restart: unless-stopped
    volumes:
      - linuxgsm-sbots:/data
    ports:

volumes:
  linuxgsm-sbots:
