version: "3.8"
services:
  # bind mount example
  linuxgsm-ns2c-bind:
    image: ghcr.io/gameservermanagers/gameserver:ns2c
    container_name: ns2cserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-ns2c-volume:
    image: ghcr.io/gameservermanagers/gameserver:ns2c
    container_name: ns2cserver
    restart: unless-stopped
    volumes:
      - linuxgsm-ns2c:/data
    ports:

volumes:
  linuxgsm-ns2c:
