version: "3.8"
services:
  # bind mount example
  linuxgsm-av-bind:
    image: ghcr.io/gameservermanagers/gameserver:av
    container_name: avserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-av-volume:
    image: ghcr.io/gameservermanagers/gameserver:av
    container_name: avserver
    restart: unless-stopped
    volumes:
      - linuxgsm-av:/data
    ports:

volumes:
  linuxgsm-av:
