version: "3.8"
services:
  # bind mount example
  linuxgsm-jk2-bind:
    image: gameservermanagers/gameserver:jk2
    # image: ghcr.io/gameservermanagers/gameserver:jk2
    container_name: jk2server
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-jk2-volume:
    image: gameservermanagers/gameserver:jk2
    # image: ghcr.io/gameservermanagers/gameserver:jk2
    container_name: jk2server
    restart: unless-stopped
    volumes:
      - linuxgsm-jk2:/data
    ports:

volumes:
  linuxgsm-jk2:
