version: "3.8"
services:
  linuxgsm-dmc:
    image: ghcr.io/gameservermanagers/gameserver:dmc
    container_name: dmcserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
