version: "3.8"
services:
  linuxgsm-arma3:
    image: ghcr.io/gameservermanagers/gameserver:arma3
    container_name: arma3server
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
