version: "3.8"
services:
  # bind mount example
  linuxgsm-cs-bind:
    image: ghcr.io/gameservermanagers/gameserver:cs
    container_name: csserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-cs-volume:
    image: ghcr.io/gameservermanagers/gameserver:cs
    container_name: csserver
    restart: unless-stopped
    volumes:
      - linuxgsm-cs:/data
    ports:

volumes:
  linuxgsm-cs:
