version: "3.8"
services:
  # bind mount example
  linuxgsm-q2-bind:
    image: ghcr.io/gameservermanagers/gameserver:q2
    container_name: q2server
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-q2-volume:
    image: ghcr.io/gameservermanagers/gameserver:q2
    container_name: q2server
    restart: unless-stopped
    volumes:
      - linuxgsm-q2:/data
    ports:

volumes:
  linuxgsm-q2:
