version: "3.8"
services:
  linuxgsm-tw:
    image: ghcr.io/gameservermanagers/gameserver:tw
    container_name: twserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
