version: "3.8"
services:
  linuxgsm-vpmc:
    image: ghcr.io/gameservermanagers/gameserver:vpmc
    container_name: vpmcserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
