version: "3.8"
services:
  # bind mount example
  linuxgsm-nmrih-bind:
    image: gameservermanagers/gameserver:nmrih
    # image: ghcr.io/gameservermanagers/gameserver:nmrih
    container_name: nmrihserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/nmrihserver:/data
    ports:

  # volume example
  linuxgsm-nmrih-volume:
    image: gameservermanagers/gameserver:nmrih
    # image: ghcr.io/gameservermanagers/gameserver:nmrih
    container_name: nmrihserver
    restart: unless-stopped
    volumes:
      - linuxgsm-nmrih:/data
    ports:

volumes:
  linuxgsm-nmrih:
