version: "3.8"
services:
  linuxgsm-ohd:
    image: ghcr.io/gameservermanagers/gameserver:ohd
    container_name: ohdserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
