version: "3.8"
services:
  # bind mount example
  linuxgsm-mc-bind:
    image: ghcr.io/gameservermanagers/gameserver:mc
    container_name: mcserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-mc-volume:
    image: ghcr.io/gameservermanagers/gameserver:mc
    container_name: mcserver
    restart: unless-stopped
    volumes:
      - linuxgsm-mc:/data
    ports:

volumes:
  linuxgsm-mc:
