version: "3.8"
services:
  linuxgsm-nmrih:
    image: ghcr.io/gameservermanagers/gameserver:nmrih
    container_name: nmrihserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
