version: "3.8"
services:
  # bind mount example
  linuxgsm-mcb-bind:
    image: gameservermanagers/gameserver:mcb
    # image: ghcr.io/gameservermanagers/gameserver:mcb
    container_name: mcbserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/mcbserver:/data
    ports:

  # volume example
  linuxgsm-mcb-volume:
    image: gameservermanagers/gameserver:mcb
    # image: ghcr.io/gameservermanagers/gameserver:mcb
    container_name: mcbserver
    restart: unless-stopped
    volumes:
      - linuxgsm-mcb:/data
    ports:

volumes:
  linuxgsm-mcb:
