version: "3.8"
services:
  # bind mount example
  linuxgsm-ets2-bind:
    image: gameservermanagers/gameserver:ets2
    # image: ghcr.io/gameservermanagers/gameserver:ets2
    container_name: ets2server
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-ets2-volume:
    image: gameservermanagers/gameserver:ets2
    # image: ghcr.io/gameservermanagers/gameserver:ets2
    container_name: ets2server
    restart: unless-stopped
    volumes:
      - linuxgsm-ets2:/data
    ports:

volumes:
  linuxgsm-ets2:
