version: "3.8"
services:
  # bind mount example
  linuxgsm-mh-bind:
    image: gameservermanagers/gameserver:mh
    # image: ghcr.io/gameservermanagers/gameserver:mh
    container_name: mhserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/mhserver:/data
    ports:

  # volume example
  linuxgsm-mh-volume:
    image: gameservermanagers/gameserver:mh
    # image: ghcr.io/gameservermanagers/gameserver:mh
    container_name: mhserver
    restart: unless-stopped
    volumes:
      - linuxgsm-mh:/data
    ports:

volumes:
  linuxgsm-mh:
