version: "3.8"
services:
  # bind mount example
  linuxgsm-ns-bind:
    image: gameservermanagers/gameserver:ns
    # image: ghcr.io/gameservermanagers/gameserver:ns
    container_name: nsserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-ns-volume:
    image: gameservermanagers/gameserver:ns
    # image: ghcr.io/gameservermanagers/gameserver:ns
    container_name: nsserver
    restart: unless-stopped
    volumes:
      - linuxgsm-ns:/data
    ports:

volumes:
  linuxgsm-ns:
