version: "3.8"
services:
  # bind mount example
  linuxgsm-codwaw-bind:
    image: gameservermanagers/gameserver:codwaw
    # image: ghcr.io/gameservermanagers/gameserver:codwaw
    container_name: codwawserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/codwawserver:/data
    ports:

  # volume example
  linuxgsm-codwaw-volume:
    image: gameservermanagers/gameserver:codwaw
    # image: ghcr.io/gameservermanagers/gameserver:codwaw
    container_name: codwawserver
    restart: unless-stopped
    volumes:
      - linuxgsm-codwaw:/data
    ports:

volumes:
  linuxgsm-codwaw:
