version: "3.8"
services:
  # bind mount example
  linuxgsm-stn-bind:
    image: ghcr.io/gameservermanagers/gameserver:stn
    container_name: stnserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-stn-volume:
    image: ghcr.io/gameservermanagers/gameserver:stn
    container_name: stnserver
    restart: unless-stopped
    volumes:
      - linuxgsm-stn:/data
    ports:

volumes:
  linuxgsm-stn:
