version: "3.8"
services:
  linuxgsm-jc2:
    image: ghcr.io/gameservermanagers/gameserver:jc2
    container_name: jc2server
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
