version: "3.8"
services:
  # bind mount example
  linuxgsm-ios-bind:
    image: ghcr.io/gameservermanagers/gameserver:ios
    container_name: iosserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-ios-volume:
    image: ghcr.io/gameservermanagers/gameserver:ios
    container_name: iosserver
    restart: unless-stopped
    volumes:
      - linuxgsm-ios:/data
    ports:

volumes:
  linuxgsm-ios:
