version: "3.8"
services:
  # bind mount example
  linuxgsm-rw-bind:
    image: ghcr.io/gameservermanagers/gameserver:rw
    container_name: rwserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-rw-volume:
    image: ghcr.io/gameservermanagers/gameserver:rw
    container_name: rwserver
    restart: unless-stopped
    volumes:
      - linuxgsm-rw:/data
    ports:

volumes:
  linuxgsm-rw:
