version: "3.8"
services:
  # bind mount example
  linuxgsm-sven-bind:
    image: gameservermanagers/gameserver:sven
    # image: ghcr.io/gameservermanagers/gameserver:sven
    container_name: svenserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-sven-volume:
    image: gameservermanagers/gameserver:sven
    # image: ghcr.io/gameservermanagers/gameserver:sven
    container_name: svenserver
    restart: unless-stopped
    volumes:
      - linuxgsm-sven:/data
    ports:

volumes:
  linuxgsm-sven:
