version: "3.8"
services:
  linuxgsm-ut99:
    image: ghcr.io/gameservermanagers/gameserver:ut99
    container_name: ut99server
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
