version: "3.8"
services:
  # bind mount example
  linuxgsm-dmc-bind:
    image: gameservermanagers/gameserver:dmc
    # image: ghcr.io/gameservermanagers/gameserver:dmc
    container_name: dmcserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-dmc-volume:
    image: gameservermanagers/gameserver:dmc
    # image: ghcr.io/gameservermanagers/gameserver:dmc
    container_name: dmcserver
    restart: unless-stopped
    volumes:
      - linuxgsm-dmc:/data
    ports:

volumes:
  linuxgsm-dmc:
