version: "3.8"
services:
  # bind mount example
  linuxgsm-squad-bind:
    image: gameservermanagers/gameserver:squad
    # image: ghcr.io/gameservermanagers/gameserver:squad
    container_name: squadserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-squad-volume:
    image: gameservermanagers/gameserver:squad
    # image: ghcr.io/gameservermanagers/gameserver:squad
    container_name: squadserver
    restart: unless-stopped
    volumes:
      - linuxgsm-squad:/data
    ports:

volumes:
  linuxgsm-squad:
