version: "3.8"
services:
  # bind mount example
  linuxgsm-sf-bind:
    image: gameservermanagers/gameserver:sf
    # image: ghcr.io/gameservermanagers/gameserver:sf
    container_name: sfserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/sfserver:/data
    ports:

  # volume example
  linuxgsm-sf-volume:
    image: gameservermanagers/gameserver:sf
    # image: ghcr.io/gameservermanagers/gameserver:sf
    container_name: sfserver
    restart: unless-stopped
    volumes:
      - linuxgsm-sf:/data
    ports:

volumes:
  linuxgsm-sf:
