version: "3.8"
services:
  # bind mount example
  linuxgsm-pc-bind:
    image: gameservermanagers/gameserver:pc
    # image: ghcr.io/gameservermanagers/gameserver:pc
    container_name: pcserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-pc-volume:
    image: gameservermanagers/gameserver:pc
    # image: ghcr.io/gameservermanagers/gameserver:pc
    container_name: pcserver
    restart: unless-stopped
    volumes:
      - linuxgsm-pc:/data
    ports:

volumes:
  linuxgsm-pc:
