version: "3.8"
services:
  linuxgsm-coduo:
    image: ghcr.io/gameservermanagers/gameserver:coduo
    container_name: coduoserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
