version: "3.8"
services:
  linuxgsm-cod:
    image: ghcr.io/gameservermanagers/gameserver:cod
    container_name: codserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
