version: "3.8"
services:
  # bind mount example
  linuxgsm-dodr-bind:
    image: gameservermanagers/gameserver:dodr
    # image: ghcr.io/gameservermanagers/gameserver:dodr
    container_name: dodrserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/dodrserver:/data
    ports:

  # volume example
  linuxgsm-dodr-volume:
    image: gameservermanagers/gameserver:dodr
    # image: ghcr.io/gameservermanagers/gameserver:dodr
    container_name: dodrserver
    restart: unless-stopped
    volumes:
      - linuxgsm-dodr:/data
    ports:

volumes:
  linuxgsm-dodr:
