version: "3.8"
services:
  linuxgsm-fof:
    image: ghcr.io/gameservermanagers/gameserver:fof
    container_name: fofserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
