version: "3.8"
services:
  linuxgsm-jk2:
    image: ghcr.io/gameservermanagers/gameserver:jk2
    container_name: jk2server
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
