version: "3.8"
services:
  linuxgsm-vh:
    image: ghcr.io/gameservermanagers/gameserver:vh
    container_name: vhserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
