version: "3.8"
services:
  linuxgsm-hldm:
    image: ghcr.io/gameservermanagers/gameserver:hldm
    container_name: hldmserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
