version: "3.8"
services:
  # bind mount example
  linuxgsm-arma3-bind:
    image: gameservermanagers/gameserver:arma3
    # image: ghcr.io/gameservermanagers/gameserver:arma3
    container_name: arma3server
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-arma3-volume:
    image: gameservermanagers/gameserver:arma3
    # image: ghcr.io/gameservermanagers/gameserver:arma3
    container_name: arma3server
    restart: unless-stopped
    volumes:
      - linuxgsm-arma3:/data
    ports:

volumes:
  linuxgsm-arma3:
