version: "3.8"
services:
  # bind mount example
  linuxgsm-bmdm-bind:
    image: gameservermanagers/gameserver:bmdm
    # image: ghcr.io/gameservermanagers/gameserver:bmdm
    container_name: bmdmserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/bmdmserver:/data
    ports:

  # volume example
  linuxgsm-bmdm-volume:
    image: gameservermanagers/gameserver:bmdm
    # image: ghcr.io/gameservermanagers/gameserver:bmdm
    container_name: bmdmserver
    restart: unless-stopped
    volumes:
      - linuxgsm-bmdm:/data
    ports:

volumes:
  linuxgsm-bmdm:
