version: "3.8"
services:
  # bind mount example
  linuxgsm-ut99-bind:
    image: gameservermanagers/gameserver:ut99
    # image: ghcr.io/gameservermanagers/gameserver:ut99
    container_name: ut99server
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/ut99server:/data
    ports:

  # volume example
  linuxgsm-ut99-volume:
    image: gameservermanagers/gameserver:ut99
    # image: ghcr.io/gameservermanagers/gameserver:ut99
    container_name: ut99server
    restart: unless-stopped
    volumes:
      - linuxgsm-ut99:/data
    ports:

volumes:
  linuxgsm-ut99:
