version: "3.8"
services:
  linuxgsm-q3:
    image: ghcr.io/gameservermanagers/gameserver:q3
    container_name: q3server
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
