version: "3.8"
services:
  # bind mount example
  linuxgsm-sof2-bind:
    image: ghcr.io/gameservermanagers/gameserver:sof2
    container_name: sof2server
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-sof2-volume:
    image: ghcr.io/gameservermanagers/gameserver:sof2
    container_name: sof2server
    restart: unless-stopped
    volumes:
      - linuxgsm-sof2:/data
    ports:

volumes:
  linuxgsm-sof2:
