version: "3.8"
services:
  # bind mount example
  linuxgsm-vs-bind:
    image: gameservermanagers/gameserver:vs
    # image: ghcr.io/gameservermanagers/gameserver:vs
    container_name: vsserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/vsserver:/data
    ports:

  # volume example
  linuxgsm-vs-volume:
    image: gameservermanagers/gameserver:vs
    # image: ghcr.io/gameservermanagers/gameserver:vs
    container_name: vsserver
    restart: unless-stopped
    volumes:
      - linuxgsm-vs:/data
    ports:

volumes:
  linuxgsm-vs:
