version: "3.8"
services:
  linuxgsm-armar:
    image: ghcr.io/gameservermanagers/gameserver:armar
    container_name: armarserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
