version: "3.8"
services:
  linuxgsm-fctr:
    image: ghcr.io/gameservermanagers/gameserver:fctr
    container_name: fctrserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
