version: "3.8"
services:
  # bind mount example
  linuxgsm-ark-bind:
    image: ghcr.io/gameservermanagers/gameserver:ark
    container_name: arkserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-ark-volume:
    image: ghcr.io/gameservermanagers/gameserver:ark
    container_name: arkserver
    restart: unless-stopped
    volumes:
      - linuxgsm-ark:/data
    ports:

volumes:
  linuxgsm-ark:
