version: "3.8"
services:
  # bind mount example
  linuxgsm-doi-bind:
    image: gameservermanagers/gameserver:doi
    # image: ghcr.io/gameservermanagers/gameserver:doi
    container_name: doiserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-doi-volume:
    image: gameservermanagers/gameserver:doi
    # image: ghcr.io/gameservermanagers/gameserver:doi
    container_name: doiserver
    restart: unless-stopped
    volumes:
      - linuxgsm-doi:/data
    ports:

volumes:
  linuxgsm-doi:
