version: "3.8"
services:
  linuxgsm-hl2dm:
    image: ghcr.io/gameservermanagers/gameserver:hl2dm
    container_name: hl2dmserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
