version: "3.8"
services:
  # bind mount example
  linuxgsm-bb-bind:
    image: gameservermanagers/gameserver:bb
    # image: ghcr.io/gameservermanagers/gameserver:bb
    container_name: bbserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/bbserver:/data
    ports:

  # volume example
  linuxgsm-bb-volume:
    image: gameservermanagers/gameserver:bb
    # image: ghcr.io/gameservermanagers/gameserver:bb
    container_name: bbserver
    restart: unless-stopped
    volumes:
      - linuxgsm-bb:/data
    ports:

volumes:
  linuxgsm-bb:
