version: "3.8"
services:
  # bind mount example
  linuxgsm-tfc-bind:
    image: gameservermanagers/gameserver:tfc
    # image: ghcr.io/gameservermanagers/gameserver:tfc
    container_name: tfcserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/tfcserver:/data
    ports:

  # volume example
  linuxgsm-tfc-volume:
    image: gameservermanagers/gameserver:tfc
    # image: ghcr.io/gameservermanagers/gameserver:tfc
    container_name: tfcserver
    restart: unless-stopped
    volumes:
      - linuxgsm-tfc:/data
    ports:

volumes:
  linuxgsm-tfc:
