version: "3.8"
services:
  # bind mount example
  linuxgsm-wurm-bind:
    image: gameservermanagers/gameserver:wurm
    # image: ghcr.io/gameservermanagers/gameserver:wurm
    container_name: wurmserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-wurm-volume:
    image: gameservermanagers/gameserver:wurm
    # image: ghcr.io/gameservermanagers/gameserver:wurm
    container_name: wurmserver
    restart: unless-stopped
    volumes:
      - linuxgsm-wurm:/data
    ports:

volumes:
  linuxgsm-wurm:
