version: "3.8"
services:
  # bind mount example
  linuxgsm-tw-bind:
    image: gameservermanagers/gameserver:tw
    # image: ghcr.io/gameservermanagers/gameserver:tw
    container_name: twserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-tw-volume:
    image: gameservermanagers/gameserver:tw
    # image: ghcr.io/gameservermanagers/gameserver:tw
    container_name: twserver
    restart: unless-stopped
    volumes:
      - linuxgsm-tw:/data
    ports:

volumes:
  linuxgsm-tw:
