version: "3.8"
services:
  # bind mount example
  linuxgsm-dod-bind:
    image: gameservermanagers/gameserver:dod
    # image: ghcr.io/gameservermanagers/gameserver:dod
    container_name: dodserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/dodserver:/data
    ports:

  # volume example
  linuxgsm-dod-volume:
    image: gameservermanagers/gameserver:dod
    # image: ghcr.io/gameservermanagers/gameserver:dod
    container_name: dodserver
    restart: unless-stopped
    volumes:
      - linuxgsm-dod:/data
    ports:

volumes:
  linuxgsm-dod:
