version: "3.8"
services:
  linuxgsm-ahl2:
    image: ghcr.io/gameservermanagers/gameserver:ahl2
    container_name: ahl2server
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
