version: "3.8"
services:
  # bind mount example
  linuxgsm-vpmc-bind:
    image: gameservermanagers/gameserver:vpmc
    # image: ghcr.io/gameservermanagers/gameserver:vpmc
    container_name: vpmcserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-vpmc-volume:
    image: gameservermanagers/gameserver:vpmc
    # image: ghcr.io/gameservermanagers/gameserver:vpmc
    container_name: vpmcserver
    restart: unless-stopped
    volumes:
      - linuxgsm-vpmc:/data
    ports:

volumes:
  linuxgsm-vpmc:
