version: "3.8"
services:
  linuxgsm-css:
    image: ghcr.io/gameservermanagers/gameserver:css
    container_name: cssserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
