version: "3.8"
services:
  linuxgsm-pvr:
    image: ghcr.io/gameservermanagers/gameserver:pvr
    container_name: pvrserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
