version: "3.8"
services:
  linuxgsm-gmod:
    image: ghcr.io/gameservermanagers/gameserver:gmod
    container_name: gmodserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
