version: "3.8"
services:
  linuxgsm-ns2:
    image: ghcr.io/gameservermanagers/gameserver:ns2
    container_name: ns2server
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
