version: "3.8"
services:
  # bind mount example
  linuxgsm-nd-bind:
    image: gameservermanagers/gameserver:nd
    # image: ghcr.io/gameservermanagers/gameserver:nd
    container_name: ndserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/ndserver:/data
    ports:

  # volume example
  linuxgsm-nd-volume:
    image: gameservermanagers/gameserver:nd
    # image: ghcr.io/gameservermanagers/gameserver:nd
    container_name: ndserver
    restart: unless-stopped
    volumes:
      - linuxgsm-nd:/data
    ports:

volumes:
  linuxgsm-nd:
