version: "3.8"
services:
  linuxgsm-ro:
    image: ghcr.io/gameservermanagers/gameserver:ro
    container_name: roserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
