version: "3.8"
services:
  # bind mount example
  linuxgsm-dst-bind:
    image: ghcr.io/gameservermanagers/gameserver:dst
    container_name: dstserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-dst-volume:
    image: ghcr.io/gameservermanagers/gameserver:dst
    container_name: dstserver
    restart: unless-stopped
    volumes:
      - linuxgsm-dst:/data
    ports:

volumes:
  linuxgsm-dst:
