version: "3.8"
services:
  linuxgsm-scpslsm:
    image: ghcr.io/gameservermanagers/gameserver:scpslsm
    container_name: scpslsmserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
