version: "3.8"
services:
  # bind mount example
  linuxgsm-ut-bind:
    image: ghcr.io/gameservermanagers/gameserver:ut
    container_name: utserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-ut-volume:
    image: ghcr.io/gameservermanagers/gameserver:ut
    container_name: utserver
    restart: unless-stopped
    volumes:
      - linuxgsm-ut:/data
    ports:

volumes:
  linuxgsm-ut:
