version: "3.8"
services:
  linuxgsm-wmc:
    image: ghcr.io/gameservermanagers/gameserver:wmc
    container_name: wmcserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
