version: "3.8"
services:
  linuxgsm-ti:
    image: ghcr.io/gameservermanagers/gameserver:ti
    container_name: tiserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
