version: "3.8"
services:
  # bind mount example
  linuxgsm-dys-bind:
    image: gameservermanagers/gameserver:dys
    # image: ghcr.io/gameservermanagers/gameserver:dys
    container_name: dysserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:

  # volume example
  linuxgsm-dys-volume:
    image: gameservermanagers/gameserver:dys
    # image: ghcr.io/gameservermanagers/gameserver:dys
    container_name: dysserver
    restart: unless-stopped
    volumes:
      - linuxgsm-dys:/data
    ports:

volumes:
  linuxgsm-dys:
