version: "3.8"
services:
  linuxgsm-cs:
    image: ghcr.io/gameservermanagers/gameserver:cs
    container_name: csserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
