version: "3.8"
services:
  linuxgsm-eco:
    image: ghcr.io/gameservermanagers/gameserver:eco
    container_name: ecoserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
