version: "3.8"
services:
  linuxgsm-wurm:
    image: ghcr.io/gameservermanagers/gameserver:wurm
    container_name: wurmserver
    restart: unless-stopped
    volumes:
      - /path/to/linuxgsm/etlserver:/data
    ports:
