name: Generate Dockerfile
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate-dockerfiles:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies
      - run: pip3 install -r requirements.txt

      - name: Generate Dockerfile with generate-dockerfiles.sh
        run: ./generate-dockerfiles.sh

      - name: Push commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate Dockerfile"
          add: "dockerfiles/Dockerfile*"

      - id: set-matrix
        run: echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT
  docker-publish:
    needs: generate-dockerfiles
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs. generate-dockerfiles.outputs.matrix) }}
    steps:
      - run: build
