---
name: Generate Dockerfile

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout template branch
        uses: actions/checkout@v2

      - name: Generate Dockerfile file
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: Dockerfile.j2
          output_file: dockerfiles/Dockerfile.vh
          strict: true
          variables: |
            gamename="Valheim"
            shortname="vh"
            distro="ubuntu-2204"

      - name: Push commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate Dockerfile"
          add: "Dockerfile*"
