---
name: Generate Dockerfile

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Create Branch from template branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "jc3"
          sha: "empty"

      - name: Checkout template branch
        uses: actions/checkout@v2
        with:
          path: "template"
          ref: "template"

      - name: Checkout template branch
        uses: actions/checkout@v2
        with:
          path: "jc3"
          ref: "jc3"

      - name: Generate Dockerfile file
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: template/Dockerfile.j2
          output_file: jc3/Dockerfile
          strict: true
          variables: |
            gamename="Just Cause 3"
            shortname="jc3"
            distro="ubuntu-2204"

      - name: Push commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate Dockerfile"
          add: "Dockerfile"
          cwd: "./jc3/"
