name: Generate Dockerfile
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate-dockerfiles:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip" # caching pip dependencies
      - run: pip3 install -r requirements.txt

      - name: Generate Dockerfile with generate-dockerfiles.sh
        run: ./generate-dockerfiles.sh

      - name: Push commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate Dockerfile"
          add: "dockerfiles/Dockerfile*"

      - id: set-matrix
        run: echo "matrix={\"include\":[{\"shortname\":\"ac\"},{\"shortname\":\"ahl\"},{\"shortname\":\"ahl2\"},{\"shortname\":\"ark\"},{\"shortname\":\"arma3\"},{\"shortname\":\"armar\"},{\"shortname\":\"av\"},{\"shortname\":\"bb\"},{\"shortname\":\"bb2\"},{\"shortname\":\"bd\"},{\"shortname\":\"bf1942\"},{\"shortname\":\"bfv\"},{\"shortname\":\"bmdm\"},{\"shortname\":\"bo\"},{\"shortname\":\"bs\"},{\"shortname\":\"bt\"},{\"shortname\":\"bt1944\"},{\"shortname\":\"cc\"},{\"shortname\":\"cd\"},{\"shortname\":\"cmw\"},{\"shortname\":\"cod\"},{\"shortname\":\"cod2\"},{\"shortname\":\"cod4\"},{\"shortname\":\"coduo\"},{\"shortname\":\"codwaw\"},{\"shortname\":\"col\"},{\"shortname\":\"cs\"},{\"shortname\":\"cscz\"},{\"shortname\":\"csgo\"},{\"shortname\":\"css\"},{\"shortname\":\"dab\"},{\"shortname\":\"dayz\"},{\"shortname\":\"dmc\"},{\"shortname\":\"dod\"},{\"shortname\":\"dodr\"},{\"shortname\":\"dods\"},{\"shortname\":\"doi\"},{\"shortname\":\"dst\"},{\"shortname\":\"dys\"},{\"shortname\":\"eco\"},{\"shortname\":\"em\"},{\"shortname\":\"etl\"},{\"shortname\":\"fctr\"},{\"shortname\":\"fof\"},{\"shortname\":\"gmod\"},{\"shortname\":\"hl2dm\"},{\"shortname\":\"hldm\"},{\"shortname\":\"hldms\"},{\"shortname\":\"hw\"},{\"shortname\":\"ins\"},{\"shortname\":\"inss\"},{\"shortname\":\"ios\"},{\"shortname\":\"jc2\"},{\"shortname\":\"jc3\"},{\"shortname\":\"jk2\"},{\"shortname\":\"kf\"},{\"shortname\":\"kf2\"},{\"shortname\":\"lo\"},{\"shortname\":\"l4d\"},{\"shortname\":\"l4d2\"},{\"shortname\":\"mc\"},{\"shortname\":\"mcb\"},{\"shortname\":\"mh\"},{\"shortname\":\"mohaa\"},{\"shortname\":\"mom\"},{\"shortname\":\"mta\"},{\"shortname\":\"mumble\"},{\"shortname\":\"nd\"},{\"shortname\":\"nmrih\"},{\"shortname\":\"ns\"},{\"shortname\":\"ns2\"},{\"shortname\":\"ns2c\"},{\"shortname\":\"onset\"},{\"shortname\":\"opfor\"},{\"shortname\":\"pc\"},{\"shortname\":\"pc2\"},{\"shortname\":\"pmc\"},{\"shortname\":\"pstbs\"},{\"shortname\":\"pvkii\"},{\"shortname\":\"pvr\"},{\"shortname\":\"pz\"},{\"shortname\":\"q2\"},{\"shortname\":\"q3\"},{\"shortname\":\"ql\"},{\"shortname\":\"qw\"},{\"shortname\":\"ricochet\"},{\"shortname\":\"ro\"},{\"shortname\":\"rtcw\"},{\"shortname\":\"rust\"},{\"shortname\":\"rw\"},{\"shortname\":\"samp\"},{\"shortname\":\"sb\"},{\"shortname\":\"sbots\"},{\"shortname\":\"scpsl\"},{\"shortname\":\"scpslsm\"},{\"shortname\":\"sdtd\"},{\"shortname\":\"sfc\"},{\"shortname\":\"sf\"},{\"shortname\":\"sof2\"},{\"shortname\":\"sol\"},{\"shortname\":\"squad\"},{\"shortname\":\"st\"},{\"shortname\":\"stn\"},{\"shortname\":\"sven\"},{\"shortname\":\"terraria\"},{\"shortname\":\"tf2\"},{\"shortname\":\"tfc\"},{\"shortname\":\"ti\"},{\"shortname\":\"ts\"},{\"shortname\":\"ts3\"},{\"shortname\":\"tu\"},{\"shortname\":\"tw\"},{\"shortname\":\"unt\"},{\"shortname\":\"ut\"},{\"shortname\":\"ut2k4\"},{\"shortname\":\"ut3\"},{\"shortname\":\"ut99\"},{\"shortname\":\"vh\"},{\"shortname\":\"vints\"},{\"shortname\":\"vpmc\"},{\"shortname\":\"vs\"},{\"shortname\":\"wet\"},{\"shortname\":\"wf\"},{\"shortname\":\"wmc\"},{\"shortname\":\"wurm\"},{\"shortname\":\"zmr\"},{\"shortname\":\"zps\"}]}" >> $GITHUB_OUTPUT
  docker-publish:
    needs: generate-dockerfiles
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.generate-dockerfiles.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1
      - name: Login to DockerHub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            gameservermanagers/gameserver:${{ matrix.shortname }}
            ghcr.io/gameservermanagers/gameserver:${{ matrix.shortname }}
